baseURL = "maknotavailable.github.io"
languageCode = "en-us"
title = "MAK Site"
theme = "hallo"
[Author]
    name = "martin"
[params]
    [params.colors]
        background = "#000000"
        foreground = "#edf7ff"
        hover = "#ffba82"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/maknotavailable"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/maknotavailable"
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://linkedin.com/in/mkayser"